{"name": "Проверка ошибки при попытке авторизации с некорректным паролем", "status": "passed", "start": 1727636419047, "stop": 1727636419582, "uuid": "33f8f958-797f-44a7-a858-58d0e100fd26", "historyId": "7b712df357c22f0662c32513571c68e2", "testCaseId": "7b712df357c22f0662c32513571c68e2", "fullName": "tests.test_login_user.TestLoginUser#test_invalid_password_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Notebook"}, {"name": "thread", "value": "26536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}