{"name": "Проверка ошибки при создании заказа с несколькими ингредиентами", "status": "passed", "start": 1727636403964, "stop": 1727636404996, "uuid": "ab3c0f15-5ae1-4f02-b47d-340a94749f5a", "historyId": "01fca61b37023382370ae49f74fd2397", "testCaseId": "01fca61b37023382370ae49f74fd2397", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_wrong_ingredient_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "Notebook"}, {"name": "thread", "value": "26536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}